from airflow.models import Variable

BUCKET_NAME = Variable.get("BUCKET_NAME")
CUSTOMERS_DATASET_TABLE=Variable.get("CUSTOMERS_DATASET_TABLE")
CUSTOMERS_DATASET_STAGING_TABLE=Variable.get("CUSTOMERS_DATASET_STAGING_TABLE")
CUSTOMERS_FOLDER_PATH = Variable.get("CUSTOMERS_FOLDER_PATH")
SALES_FOLDER_PATH = Variable.get("SALES_FOLDER_PATH")
SALES_DATASET_TABLE=Variable.get("SALES_DATASET_TABLE")
SALES_DATASET_STAGING_TABLE=Variable.get("SALES_DATASET_STAGING_TABLE")
USER_PROFILES_PATH=Variable.get("USER_PROFILES_PATH")
USER_PROFILES_SILVER_DATASET_TABLES=Variable.get("USER_PROFILES_SILVER_DATASET_TABLES")
