from airflow.models import Variable

BUCKET_NAME = Variable.get("BUCKET_NAME")
SALES_FOLDER_PATH = Variable.get("SALES_FOLDER_PATH")
PROJECT_DATASET_TABLE=Variable.get("PROJECT_DATASET_TABLE")
PROJECT_DATASET_STAGING_TABLE=Variable.get("PROJECT_DATASET_STAGING_TABLE")
